### ISSUE TITLE
Discretize uniform count not possible for integer arrays

### ISSUE THREAD

**Issue by Tchanders** [sisl/Discretizers.jl#2]
Hi, is there a reason why binedges has no method for discretising integer arrays with a uniform count?

**Comment by tawheeler** [comment]
No. I was worried about the repeated value problem and associated edge cases.
Feel free to submit a PR, otherwise I can get to it some time.

**Comment by tawheeler** [comment]
Okay, I added some basic functionality in commit 483244e.
