### ISSUE TITLE
get_histogram_plot_arrays not working?

### ISSUE THREAD

**Issue by ljschumacher** [sisl/Discretizers.jl#22]
I was running the notebook and encountered the following problem

`using PGFPlots
using Distributions

data = [rand(Cauchy(-5, 1.8), 500);
        rand(Cauchy(-4, 0.8), 2000);
        rand(Cauchy(-1, 0.3), 500);
        rand(Cauchy( 2, 0.8), 1000);
        rand(Cauchy( 4, 1.5), 500)]
data = filter!(x->-15.0 <= x <= 15.0, data)

g = GroupPlot(3, 1, groupStyle = "horizontal sep = 1.75cm")

discalgs = [("Uniform Width", DiscretizeUniformWidth(15)),
            ("Bayesian Blocks", DiscretizeBayesianBlocks())]

for (name, discalg) in discalgs
    disc = LinearDiscretizer(binedges(discalg, data))
    counts = get_discretization_counts(disc, data)    
    arr_x, arr_y = get_histogram_plot_arrays(disc.binedges, counts ./ binwidths(disc))
    push!(g, Axis(Plots.Linear(arr_x, convert(Vector{Float64}, arr_y), style="const plot, mark=none, fill=blue!60"), 
          ymin=0, xlabel="x", ylabel="pdf(x)", title=name))
end`

I got the following error
`MethodError: no method matching Array{Float64,N} where N(::Int64)
Closest candidates are:
  Array{Float64,N} where N(!Matched::UndefInitializer, !Matched::Int64) where T at boot.jl:416
  Array{Float64,N} where N(!Matched::UndefInitializer, !Matched::Int64, !Matched::Int64) where T at boot.jl:417
  Array{Float64,N} where N(!Matched::UndefInitializer, !Matched::Int64, !Matched::Int64, !Matched::Int64) where T at boot.jl:418
  ...

Stacktrace:
 [1] get_histogram_plot_arrays(::Array{Float64,1}, ::Array{Float64,1}) at /Users/.../.juliapro/JuliaPro_v1.1.1.1/packages/Discretizers/tKxLS/src/common.jl:57
 [2] top-level scope at ./In[4]:21`

**Comment by mykelk** [comment]
It's fixed now on master. @tawheeler if you are happy with it, you can tag a release. I think it would be good to add the `Project.toml` and set up `JuliaRegistrator`.

**Comment by mykelk** [comment]
Fixed in version 3.1.0.
