### ISSUE TITLE
What are the dictionaries in LinearDiscretizer for?

### ISSUE THREAD

**Issue by zsunberg** [sisl/Discretizers.jl#24]
My code is spending most of its time looking up things in these dictionaries, but they just seem to be mapping straight through, i.e. 1=>1, 2=>2, etc.

**Comment by mykelk** [comment]
I agree. I think this is best implemented as a `Vector`. Perhaps @tawheeler has an idea why it is implemented as a `Dict`?

**Comment by tawheeler** [comment]
The discretizers let you use encoding types. So if you wanted to map to UInt8 instead of Int, this map was a way to do that. Its not really useful, and its mainly an artifact of categorical discretizer.
