### ISSUE TITLE
update datastrucres in project toml

### ISSUE THREAD

**Issue by Datseris** [sisl/Discretizers.jl#30]
Please update DataStructures to 0.18 to project toml and tag a new version ASAP. Packages that use Discretizers can't be installed in  the same environment with DifferentialEquations because it needs DataStructutres 0.18.

also please consider installing CompatHelper.jl so that this is automated

**Comment by mykelk** [comment]
Added and triggered creation of new version. @mossr would you mind setting up CompatHelper?

**Comment by mossr** [comment]
I can do that, no problem

**Comment by Datseris** [comment]
thank you!
