### ISSUE TITLE
Bayesian blocks algorithm

### ISSUE THREAD

**Issue by Tchanders** [sisl/Discretizers.jl#5]
Bayesian blocks is a nice algorithm that we've been using in my research group - Python examples and explanation here: http://www.astroml.org/examples/algorithms/plot_bayesian_blocks.html

Could be a good addition to this package?

**Comment by mykelk** [comment]
Absolutely! Feel free to submit a PR. I think a lot of people would enjoy using it.

**Comment by tawheeler** [comment]
Thanks for implementing!
It looks like the first and last edges of the discretization are a bit weird.
I was in the process of adding a visualization to the docs and noticed this.

![image](https://cloud.githubusercontent.com/assets/3334079/17280855/ff35d228-574a-11e6-9980-f85934e2da66.png)

The edges are: [-15.0,-14.911558915720722,-9.905993815470893,-8.15771193948401,-6.968754643502925,-5.494738734758997,-5.132272775520218,-4.329782700715244,-3.833320871435708,-3.2954145533104855,-2.41189147400773,-1.4802781796428444,-0.7076665597226628,-0.4108910755481662,0.821472839716015,1.3345687803295885,2.5955171118962954,4.539389411294254,5.858291382204798,8.869899672002305,14.988695528459248,15.0]

```
using Discretizers
using PGFPlots
using Distributions

# draw a set of variables and
# truncate values to a reasonable range
srand(0)
data = [rand(Cauchy(-5, 1.8), 500);
        rand(Cauchy(-4, 0.8), 2000);
        rand(Cauchy(-1, 0.3), 500);
        rand(Cauchy( 2, 0.8), 1000);
        rand(Cauchy( 4, 1.5), 500)]
data = clamp(data, -15.0, 15.0)

g = GroupPlot(3, 1, groupStyle = "horizontal sep = 1.75cm")

discalgs = [("Uniform Width", DiscretizeUniformWidth(15)),
            ("Uniform Count", DiscretizeUniformCount(15)),
            ("Bayesian Blocks", DiscretizeBayesianBlocks())]

for (name, discalg) in discalgs
    disc = LinearDiscretizer(binedges(discalg, data))
    counts = get_discretization_counts(disc, data)

    println(binedges(disc))

    arr_x, arr_y = get_histogram_plot_arrays(disc.binedges, counts ./ binwidths(disc))
    push!(g, Axis(Plots.Linear(arr_x, convert(Vector{Float64}, arr_y), style="const plot, mark=none, fill=blue!60"), ymin=0, xlabel="x", ylabel="pdf(x)", title=name))
end

g
```

**Comment by tawheeler** [comment]
Actually, now that I think about it those bins are a byproduct of clamping the data. Filtering should fix the problem.

**Comment by Tchanders** [comment]
Great, thanks for adding the documentation!

**Comment by tawheeler** [comment]
Tagging new minor version. Good work folks.
